#!/usr/bin/env python3
"""
Regenerate every results table and figure from eval_results/.

Safe to re-run at any time; outputs are overwritten. Result files that do not
exist yet are skipped, so it works both before and after the reproduction
runs under the pre-defence training environment have finished.

    python scripts/make_report.py

Writes:
    docs/results_tables.md
    experiments/submission/*.png
"""
import csv
import math
import os
import statistics
try:
    from math import comb
except ImportError:  # Python 3.7, which the flow environment uses
    from math import factorial
    def comb(n, k):
        if k < 0 or k > n:
            return 0
        return factorial(n) // (factorial(k) * factorial(n - k))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "eval_results")
FIG = os.path.join(ROOT, "experiments", "submission")
DOC = os.path.join(ROOT, "docs")
os.makedirs(FIG, exist_ok=True)
os.makedirs(DOC, exist_ok=True)

SCEN = ["Sc1_All_Low", "Sc6_Mixed_ML", "Sc3_All_Med", "Sc4_Mixed_2H", "Sc5_Mixed_1H", "Sc2_All_High"]

# Pre-defence report, Figure 9.2: collision rate per scenario, averaged over intentions.
PREDEFENCE = {
    "Heuristic + Continuous": [4.50, 6.12, 6.50, 8.50, 7.88, 6.88],
    "Heuristic + Discrete":   [3.38, 5.50, 5.25, 5.75, 6.50, 5.50],
    "Attention + Discrete":   [0.50, 1.88, 1.75, 1.38, 3.00, 2.50],
    "Attention + Continuous": [0.38, 1.12, 0.88, 0.88, 1.12, 0.88],
}

GREY, GREEN, BLUE = "#9aa5b1", "#2e7d32", "#1f5fa8"


# ------------------------------------------------------------------ stats
def fisher(a, b, n1, n2):
    """Two-sided Fisher exact test on a collisions vs b collisions."""
    A, B, C, D = a, n1 - a, b, n2 - b
    N = A + B + C + D
    p = lambda x: comb(A + B, x) * comb(C + D, A + C - x) / comb(N, A + C)
    lo, hi = max(0, A + C - (C + D)), min(A + B, A + C)
    p0 = p(A)
    return min(sum(p(x) for x in range(lo, hi + 1) if p(x) <= p0 + 1e-12), 1.0)


def wilson(c, n, z=1.96):
    if n == 0:
        return 0.0, 0.0
    ph = c / n
    d = 1 + z * z / n
    ctr = (ph + z * z / (2 * n)) / d
    hw = z * math.sqrt(ph * (1 - ph) / n + z * z / (4 * n * n)) / d
    return 100 * max(0.0, ctr - hw), 100 * (ctr + hw)


def load(tag):
    """Summary of one result file, or None if it does not exist or is incomplete."""
    f = os.path.join(RES, f"{tag}_results.csv")
    if not os.path.exists(f):
        return None
    rows = list(csv.DictReader(open(f)))
    if not rows:
        return None
    n = sum(int(r["n_episodes"]) for r in rows)
    c = sum(int(r["collisions"]) for r in rows)
    k = len(rows)
    by = {}
    for r in rows:
        by.setdefault(r["scenario"], []).append(float(r["collision_rate"]))
    return dict(
        rows=k, c=c, n=n, col=100 * c / n,
        succ=sum(float(r["success_rate"]) for r in rows) / k,
        tt=sum(float(r["avg_travel_time"]) for r in rows) / k,
        wait=sum(float(r.get("avg_waiting_time") or 0) for r in rows) / k,
        ovr=100 * sum(float(r.get("shield_override_rate") or 0) for r in rows) / k,
        by_sc={s: statistics.mean(v) for s, v in by.items()},
    )


# ------------------------------------------------------------------ markdown
out = []
w = out.append


def table(title, entries, note=None):
    w(f"### {title}\n")
    w("| Controller | Collision rate | 95% CI | Collisions | Success | Travel time | Shield overrides |")
    w("|---|---|---|---|---|---|---|")
    got = {}
    for label, tag in entries:
        s = load(tag)
        if s is None:
            continue
        got[label] = s
        lo, hi = wilson(s["c"], s["n"])
        ovr = f"{s['ovr']:.1f}%" if s["ovr"] > 0 else "-"
        w(f"| {label} | {s['col']:.2f}% | {lo:.2f}-{hi:.2f}% | {s['c']}/{s['n']} | "
          f"{s['succ']:.1f}% | {s['tt']:.1f} s | {ovr} |")
    if note:
        w(f"\n{note}")
    w("")
    return got


def pair(title, a, b):
    if a and b:
        w(f"- {title}: {a['c']} vs {b['c']} collisions, p = {fisher(a['c'], b['c'], a['n'], b['n']):.3f}")


w("# Results tables\n")
w("_Generated by `scripts/make_report.py` from `eval_results/`. Do not edit by hand._\n")
w("All evaluation uses the pre-defence protocol from `src/test/v0_1_evaluate.py`: "
  "6 traffic scenarios x 4 intention settings, 42 episodes per configuration, deterministic policy. "
  "Confidence intervals are Wilson 95% intervals; p-values are two-sided Fisher exact tests.\n")

# ---- reproduction under the pre-defence training environment ----
w("## A. Pre-defence training environment\n")
w("Models trained with `--train-profile ibrahima`, which reproduces the training environment "
  "of `src/configs/v0_1_single_agent.py`: 400 veh/h cross traffic, 275 veh/h background traffic "
  "in the agent's lane, background vehicles with speed_mode 0, RL spawn probability 0.3 and a "
  "5-step warmup. Evaluation is the same benchmark as the pre-defence report. The only remaining "
  "difference from the pre-defence models is the three leader features added to the observation "
  "after the report.\n")
repro = table("A1. Standard benchmark", [
    ("Heuristic + Discrete", "heuristic_discrete__policy_heuristic_discrete__repro"),
    ("Heuristic + Continuous", "heuristic_continous__policy_heuristic_continous__repro"),
    ("Attention + Discrete", "attention_discrete__policy_attention_discrete__repro"),
    ("Attention + Continuous", "attention_continous__policy_attention_continous__repro"),
    ("Attention + Continuous + Shield", "shielded_attention_continous__policy_attention_continous__repro"),
])
if repro:
    pair("Shield effect (same weights)", repro.get("Attention + Continuous"),
         repro.get("Attention + Continuous + Shield"))
    pair("Attention + Discrete vs Attention + Continuous", repro.get("Attention + Discrete"),
         repro.get("Attention + Continuous"))
    w("")
else:
    w("_Reproduction runs have not finished yet._\n")

# ---- current pipeline ----
w("## B. Revised training pipeline\n")
w("Models trained with the default profile: 275 veh/h cross traffic, no background traffic in the "
  "agent's lane, background vehicles with speed_mode 31, RL spawn probability 0.8 and a 50-step warmup. "
  "The training environment therefore differs from the pre-defence study; the evaluation does not.\n")
std = table("B1. Standard benchmark", [
    ("Heuristic + Discrete", "heuristic_discrete"),
    ("Heuristic + Continuous", "heuristic_continous"),
    ("Heuristic + Attention + Discrete", "heuristic_attention_discrete"),
    ("Heuristic + Attention + Continuous", "heuristic_attention_continous"),
    ("Attention + Discrete", "attention_discrete"),
    ("Attention + Continuous", "attention_continous"),
    ("Attention + Continuous + Shield (same weights)", "shielded_attention_continous__policy_attention_continous"),
    ("Attention + Discrete + Shield (same weights)", "shielded_attention_discrete__policy_attention_discrete"),
    ("Shielded, trained with shield", "shielded_attention_continous"),
])
w("Significance, standard benchmark:\n")
pair("Shield on Attention + Continuous", std.get("Attention + Continuous"),
     std.get("Attention + Continuous + Shield (same weights)"))
pair("Shield on Attention + Discrete", std.get("Attention + Discrete"),
     std.get("Attention + Discrete + Shield (same weights)"))
pair("Attention + Discrete vs Attention + Continuous", std.get("Attention + Discrete"),
     std.get("Attention + Continuous"))
pair("Heuristic + Continuous vs Attention + Continuous", std.get("Heuristic + Continuous"),
     std.get("Attention + Continuous"))
w("")

st = table("B2. High-flow traffic (550/700/850 veh/h, identical traffic across variants)", [
    ("Heuristic + Discrete", "heuristic_discrete__policy_heuristic_discrete__stress"),
    ("Heuristic + Continuous", "heuristic_continous__policy_heuristic_continous__stress"),
    ("Attention + Discrete", "attention_discrete__policy_attention_discrete__stress"),
    ("Attention + Continuous", "attention_continous__policy_attention_continous__stress_1500k"),
    ("Attention + Continuous + Shield", "shielded_attention_continous__policy_attention_continous__stress_1500k"),
    ("Attention + Continuous + Shield + commit zone", "shielded_attention_continous__policy_attention_continous__stress_commit_1500k"),
], note="Higher nominal flow did not raise collision rates, most likely because congested approaches "
        "cap how many vehicles SUMO can insert.")
w("Significance, high-flow:\n")
pair("Shield on Attention + Continuous", st.get("Attention + Continuous"),
     st.get("Attention + Continuous + Shield"))
a, b = std.get("Attention + Continuous"), std.get("Attention + Continuous + Shield (same weights)")
c, d = st.get("Attention + Continuous"), st.get("Attention + Continuous + Shield")
if a and b and c and d:
    w(f"- Shield on Attention + Continuous, all conditions combined: {a['c'] + c['c']} vs {b['c'] + d['c']} "
      f"collisions, p = {fisher(a['c'] + c['c'], b['c'] + d['c'], a['n'] + c['n'], b['n'] + d['n']):.3f}")
w("")

ext = table("B3. Extended training of Attention + Continuous to 3M steps", [
    ("Attention + Continuous, 1.5M", "attention_continous"),
    ("Attention + Continuous, 3M", "attention_continous__policy_attention_continous__3m"),
    ("Attention + Continuous, 3M + Shield", "shielded_attention_continous__policy_attention_continous__3m"),
], note="Resuming training recomputed the learning-rate schedule from the new total, raising the "
        "learning rate from 1e-5 to 1.5e-4 on resume, so this is not a clean test of longer training.")

# ---- pre-defence environment for both training and evaluation ----
w("## D. Pre-defence environment for training and evaluation\n")
w("Attention + Continuous trained with `--train-profile ibrahima` and evaluated with "
  "`--eval-profile ibrahima`, so training and evaluation both use the environment of "
  "`src/configs/v0_1_single_agent.py`: 400 veh/h cross traffic, 275 veh/h background traffic "
  "in the agent's lane, background vehicles that ignore SUMO safety checks (speed_mode 0), "
  "RL spawn probability 0.3 and a 5-step warmup. 4 intention settings x 252 episodes "
  "(1,008 per controller). Training used 24 workers with a rollout of 341 steps, keeping the "
  "batch at 8,184 samples against 8,192 in the original. The observation includes the three "
  "leader features added after the pre-defence report.\n")
cx = table("D1. Pre-defence environment", [
    ("Attention + Continuous", "attention_continous__policy_attention_continous__complex"),
    ("Attention + Continuous + Shield", "shielded_attention_continous__policy_attention_continous__complex"),
    ("Attention + Continuous + Shield (rear-aware)", "shielded_attention_continous__policy_attention_continous__complex_rear"),
], note="Rear-aware settings were fixed before evaluation: follower time gap 1.5 s, "
        "shield braking capped at -1.0 m/s2 when a follower is closer than that.")
if cx:
    pair("Shield", cx.get("Attention + Continuous"), cx.get("Attention + Continuous + Shield"))
    pair("Rear-aware shield", cx.get("Attention + Continuous"),
         cx.get("Attention + Continuous + Shield (rear-aware)"))
    w("")
else:
    w("_These runs have not finished yet._\n")

# ---- cross-study ----
w("## C. Comparison with the pre-defence study\n")
w("| Controller | Mean collision rate | Source |")
w("|---|---|---|")
cross = [(k, statistics.mean(v), "Pre-defence report, Figure 9.2") for k, v in PREDEFENCE.items()]
src = repro.get("Attention + Continuous + Shield") if repro else None
src_label = "This work, pre-defence training environment"
if src is None:
    src = std.get("Attention + Continuous + Shield (same weights)")
    src_label = "This work, revised training pipeline"
if src:
    cross.append(("Attention + Continuous + Shield", statistics.mean(src["by_sc"][s] for s in SCEN), src_label))
cross.sort(key=lambda x: -x[1])
for k, v, s in cross:
    w(f"| {k} | {v:.2f}% | {s} |")
w("")

open(os.path.join(DOC, "results_tables.md"), "w").write("\n".join(out) + "\n")


# ------------------------------------------------------------------ figures
def fig_cross():
    fig, ax = plt.subplots(figsize=(8, 4.2))
    ax.barh([k for k, _, _ in cross], [v for _, v, _ in cross],
            color=[GREY if s.startswith("Pre") else GREEN for *_, s in cross])
    for y, (_, v, _) in enumerate(cross):
        ax.text(v + 0.08, y, f"{v:.2f}%", va="center", fontsize=9)
    ax.set_xlim(0, max(v for _, v, _ in cross) * 1.13)
    ax.invert_yaxis()
    ax.set_xlabel("Mean collision rate (%)")
    ax.set_title("Collision rate on the pre-defence benchmark")
    ax.legend(handles=[Patch(color=GREY, label="Pre-defence study (reported)"),
                       Patch(color=GREEN, label=src_label)], loc="lower right", fontsize=8)
    plt.tight_layout()
    plt.savefig(os.path.join(FIG, "cross_study_collision.png"), dpi=200)
    plt.close(fig)


def fig_ci(got, name, title):
    if not got:
        return
    items = sorted(got.items(), key=lambda kv: -kv[1]["col"])
    fig, ax = plt.subplots(figsize=(8, 0.55 * len(items) + 1.4))
    for y, (k, s) in enumerate(items):
        lo, hi = wilson(s["c"], s["n"])
        col = GREEN if "Shield" in k else (GREY if "Heuristic" in k else BLUE)
        ax.plot([lo, hi], [y, y], color=col, lw=2.5)
        ax.plot(s["col"], y, "o", color=col)
        ax.text(hi + 0.08, y, f"{s['col']:.2f}%", va="center", fontsize=8)
    ax.set_yticks(range(len(items)))
    ax.set_yticklabels([k for k, _ in items], fontsize=8)
    ax.invert_yaxis()
    ax.set_xlabel("Collision rate (%) with 95% confidence interval")
    ax.set_title(title)
    plt.tight_layout()
    plt.savefig(os.path.join(FIG, name), dpi=200)
    plt.close(fig)


fig_cross()
fig_ci(std, "revised_pipeline_ci.png", "Revised training pipeline, standard benchmark")
fig_ci(repro, "predefence_env_ci.png", "Pre-defence training environment, standard benchmark")
fig_ci(cx, "predefence_env_both_ci.png", "Pre-defence environment for training and evaluation")

print("wrote docs/results_tables.md")
print("figures:", sorted(f for f in os.listdir(FIG) if f.endswith(".png")))
print("reproduction results available:", sorted(repro) if repro else "none yet")
